### PR TITLE
Initial support for Heaters

### PR DESCRIPTION
**Pull request by zyonse**
Currently a work-in-progress. The main hurdle I'm running into right now is the limited amount of control characteristics for heaters in HomeKit: https://developers.homebridge.io/#/service/HeaterCooler

I could implement something similar to the following:
Heat only thermostat accessory: Dreo 'eco' mode (set target heating temp)
Separate switch for fan only mode
Light/fan accessory to control static speed heat mode
Light/fan accessory or group of switches to control oscillation angle

Another option, implement everything into a single heater/cooler thermostat:
Off: off
Heat: Dreo 'eco' mode (set target heating temp)
Cool: fan only
Auto: static heat mode (1-3 in Dreo app)
Light/fan accessory to control oscillation angle

Would love to hear user feedback/suggestions if you have any ideas.

### CODE REVIEW

**Comment by tehlipz** [comment]
I was just looking at the Dreo Heater today and was thinking of how it would work with homebridge. I think the second option is the best, its more intuitive and also seems less clunky than having a plethora of switches for the various modes/options.

**Comment by zyonse** [comment]
@tehlipz I can't really get auto mode to work the way I want because it uses the temperature bounds set by heating and cooling modes. New proposed behavior:
Heat: Dreo 'eco' mode
Cool: fan only
Lightbulb slider: Fixed speed heating
Fan slider: Oscillation angle

**Comment by tehlipz** [comment]
I think that's reasonable, you gotta play the hand you're dealt.

**Comment by zyonse** [comment]
@tehlipz Can you test the v4.0.0 beta? You can install it by going to the manage version page in homebridge.

**Comment by tehlipz** [comment]
Oh, sorry, I havent gotten the heater yet.  Wife is still determining if she needs it or not.  I was just checking out potential compatibility with this plugin if I ended up going this route.  Sorry if I gave the wrong impression.

**Comment by zyonse** [comment]
No worries haha

**Comment by tehlipz** [comment]
Keep up the great work, your plugin is head and shoulders above the rest(HASS bridge or Starling(Google Home API) hub).

**Pull request merged**
