### PR TITLE
Ability to hide individual temperature sensors

### PR DESCRIPTION
**Pull request by alvst**
I never intended to limit the ability to hide temperature sensors for all devices only but I was didn't have time to add this functionality earlier. Now you can hide the temperature sensor for individual fans!

### CODE REVIEW

**Review by zyonse — CHANGES_REQUESTED** [review]
Can you update the README.md configuration example? Just realized we never added any of the temperature sensor changes to it.

**Comment by alvst** [comment]
Just saw this. Yes will get this done.

**Comment by alvst** [comment]
README has been updated with a new section called Features which now says: Display the temperature sensor detected within your devices (for supported devices, check your devices capabilities). Because the Dreo devices temperature sensors are not entirely accurate, you can also set a specific temperature offset for your devices.

**Review by zyonse — APPROVED** [review]

**Comment by zyonse** [comment]
After some more testing, I need you to make a few changes to make this more user friendly,

* Keep the checkbox to hide all (fan) temperature sensors
* If the checkbox is unchecked, the config ui should show a drop-down menu letting you add/remove devices that you'd like to hide
* Show a description in the config ui explaining that you can enter a device id in order to hide its individual temperature sensor

**Comment by alvst** [comment]
Based on my discussions within the Homebridge Discord when I developed this change, this is not possible since devices are automatically added when you log-into your account. Is this incorrect? Can you direct me to some documentation for this then I'd be happy to add this.

**Comment by alvst** [comment]
Specifically, since the Device ID isn't inputted into the settings screen, you can't map over the devices to create unique instances. The way I've seen other platform plugins get around this is to just log the Device ID's into the console upon installation of the plugin and NOT initiate the devices until the user adds them into the plugin settings. This then allows you to add individual settings for each.

**Comment by zyonse** [comment]
Apologies, what I meant is that I want a way for the user to be able to add multiple Device IDs from the config-ui. Ideally it should look something like this (homebridge-tplink-smarthome):

Screenshot

I would also like the "hide all temperature sensors" button from the current release to remain in place.

Feel free to open a new pull request once those changes are implemented. Sorry again for the inconvenience and thank you for your contributions to the project.

**Comment by alvst** [comment]
Ah I see, yes I can try to do that. I thought I already did but so there maybe a reason why I didn't but I can't remember. I'll let you know it may have just been in a separate branch that didn't work or I got side tracked or something.

**Pull request merged**
